### ISSUE TITLE
is scripts/annotutils redundant with analysis/annotutils?

### ISSUE THREAD

**Issue by koudyk** [neurodatascience/labelbuddy-annotations#9]

**Comment by jeromedockes** [comment]
yes it's a symbolic link to the package, so that it shows up in the
sys.path when one of the scripts is run -- this way the scripts work
without installing the annotutils package.

I am thinking we may want to flatten the analysis/ directory (ie put
everything that is in analysis/book/ directly in analysis/, remove
analysis/book/) and rely on the same mechanism for those scripts -- and
remove the setup.cfg and pyproject.toml so annotutils is not even
installable anymore. we could rename it something shorter like utils
